version: 1

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Building the Node code...
      - node -version
artifacts:
  files:
    - '**/*'
  base-directory: 'target/src'
       files:
          - index.js
          - package.json